development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: site_dev
  pool: 5
  username: root
  password: root
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: site_test
  pool: 5
  username: root
  password: root
